printq
print("i'm adding a new feature")
print("i'm adding a new feature2")
print("i'm adding a new feature3")
print("code by anu")
print("code by anu 2")
print("code by anu 3")
print("code by anu 4")
print("code by anu 5")
print("code by anu 6")
print("code by anu 7")
print("code by anu 8")
print("code by anu 9")
print("code by anu 10")